[build]
  publish = "dist"
  command = "npm run build"

# Redirect subdomain to Men's clothing page
[[redirects]]
  from = "/"
  to = "/clothes"
  status = 301
  force = true
  conditions = {Host = ["necessary.arvex.in"]}

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
