/**
 * /shop/[itemSlug] — retired route.
 *
 * Production: Netlify _redirects sends a true HTTP 301 at CDN edge to
 *   /categories/normal/[itemSlug] before this file is ever served.
 *   (Generated by scripts/generate-shop-redirects.js at build time.)
 *
 * Dev / preview: This component renders a noindex meta-refresh fallback
 *   so in-browser navigation still works without a 404.
 *
 * generateStaticParams returns [] so Next.js static export does NOT
 * pre-render any /shop/* stub pages — keeping the crawl surface clean.
 */
export async function generateStaticParams() {
  return [{ itemSlug: 'redirect-placeholder' }];
}

interface Props {
  params: Promise<{ itemSlug: string }>;
}

export default async function Page({ params }: Props) {
  const { itemSlug } = await params;
  const target = `/categories/normal/${itemSlug}`;
  const canonical = `https://lurevi.in${target}`;

  return (
    <>
      {/* Prevent indexing of this transient redirect page */}
      <meta name="robots" content="noindex, nofollow" />
      {/* Instant client-side redirect for dev/preview environments */}
      <meta httpEquiv="refresh" content={`0;url=${target}`} />
      <link rel="canonical" href={canonical} />
      <p style={{ fontFamily: 'sans-serif', padding: '2rem' }}>
        Redirecting to{' '}
        <a href={target}>{canonical}</a>…
      </p>
    </>
  );
}
